name: Ez-fastfood Infrastructure Pipeline

on:
  workflow_dispatch:
    #branches:
    #  - main
env:
  AWS_REGION: us-east-1

jobs:
  Validate:
    name: Validate terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize terraform
        run: terraform init

      - name: Validate terraform
        run: terraform validate
  
  Plan:
    name: Plan terraform changes
    runs-on: ubuntu-latest
    needs: Validate

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize terraform
      run: terraform init

    - name: Terraform plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform-artifacts
        path: |
          tfplan
          .terraform.lock.hcl

  Apply:
    name: Apply terraform changes
    runs-on: ubuntu-latest
    needs: Plan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: terraform-artifacts

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize terraform
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve tfplan

    - name: Upload Updated Terraform State
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: terraform.tfstate